### PR TITLE
Spike.new docs, extract inquirer, update options

### PR DESCRIPTION
**Pull request by jescalan**
Breaking changes in here, but they are good, promise.

### CODE REVIEW

**Comment by kylemac** [comment]
yo wtf @jescalan. our coverage went down by a thousandth of a percent!!! :rage4:

**Comment by dbox** [comment]
CANCEL THE PROJECT

**Comment by jescalan** [comment]
IT'S OVER 💥

**Comment by kylemac** [comment]
ok ok LGTM

**Pull request merged**
