### PR TITLE
More routine updates

### PR DESCRIPTION
**Pull request by jescalan**
Brings all dependencies up to date, and changes `babelConfig` to `babel`

### CODE REVIEW

**Comment by kylemac** [comment]
this'll break `spike-base` (and probably all spike projects) - we'll need to update it

**Comment by jescalan** [comment]
Yup, we'll update it when they are all released 👍

**Comment by kylemac** [comment]
:shipit:

**Comment by jescalan** [comment]
I figure we're breaking so many things right now, let's bundle this guy in while we're at it hahah 💥 💣

**Comment by kylemac** [comment]
yeah - no better time than now. lets just put a nice fat message in the release notes

**Pull request merged**
