### PR TITLE
restructure core plugins, add loader extension feature

### PR DESCRIPTION
**Pull request by jescalan**
So there is a little more work to be done here with optimizing the way the fs plugin organizes things, but this is working.

Basically, you can now add an `extension` value to any custom loader, and files will be output with that extension. The internal code was also simplified a bit and some duplication was removed.

### CODE REVIEW

**Comment by rwboyer** [comment]
FANTASTIC!!!

**Comment by rwboyer** [comment]
```
 8   module: {
  9     loaders: [{
 10       test: /\.scss$/,
 11       loaders: ['postcss-loader', 'sass-loader'],
 12       extension: 'css'
 13     }]
 14   },
```
is what's in my app.js but still app.scss is being written to  public/css instead of app.css

**Comment by jescalan** [comment]
@rwboyer it's likely that you are not accurately using this branch. there is a passing test that verifies that the `extension` property works correctly, so it's pretty unlikely that it wouldn't work for the instance you have provided. how have you set things up to use this branch in your tests?

**Comment by jescalan** [comment]
Ok so not only is this working nicely, but in the process a lot of repetitive code has been cut, and a lot of extra clarifying comments have been added. This will be released as a breaking update, but not massively breaking -- it's unlikely that it will break many peoples' builds at all, actually. But technically, it could.

**Comment by rwboyer** [comment]
@jescalan thanks for all this...  I ended up putting it my top level package file. Looked in node_modules and it LOOKED like the changes were there....

anyway is this up on npm now, if so I'll just get rid of everything and re-install to make sure everything is fresh. 

Just wanted to make sure that my usage in above config snippet was correct???

RB

**Comment by jescalan** [comment]
@rwboyer I'd add the `source-loader` as the first one in the chain, other than that looks fine!

**Comment by rwboyer** [comment]
@jescalan = think i tried it with the srouce-loader when we were disconnected on gitter on what was/was not working with my config (turns out there really wasn't a way to make it work using spikes change to get app.scss to turn into app.css in public). 

If I recall correctly for some reason that screwed up other stuff somehow... as soon as I do a fresh install I'll stick it in there and let you know what it does (especially if it breaks things as I'm fairly sure others will use the extension thing to pretty much do what I am doing, just with a slightly different set of tools wired in).

Up on npm yet?

**Comment by jescalan** [comment]
@rwboyer `spike-core@0.12.0` is up on npm. `spike` with this version has not yet shipped

**Comment by rwboyer** [comment]
okay... I'll reinstall from npm spike core underneath the other stuff and let you know how it goes...

**Comment by rwboyer** [comment]
@jescalan 

```spike-netlify-sf@0.0.1 /Volumes/LaCie2/dev/spike-netlify-sf
├── spike@0.11.1  extraneous
└─┬ spike-core@0.12.0 
  └── browser-sync@2.15.0 

here we go

**Comment by rwboyer** [comment]
@jescalan 

nope, still app.scss in public/css what the????

**Comment by jescalan** [comment]
@rwboyer this was still installed incorrectly. let's take this to gitter, this is not the right place for a support discussion!

**Comment by rwboyer** [comment]
@jescalan 

The app.scss is ACTUALLY css, it's all fine, auto-prefix is doing it's thing etc... just not renamed.


```
module.exports = {
  module: {
    loaders: [{
      test: /\.scss$/,
      loaders: ['postcss-loader', 'sass-loader'],
      extension: 'css'
    }]
  },
  devtool: 'source-map',
  ignore: ['**/layout.html', '**/_*', '**/.*', 'bower_components/'],
  reshape: (ctx) => {
    return htmlStandards({
      parser: false,
      webpack: ctx,
      locals: {
        foo: 'bar'
      }
    })
  },
  postcss: (ctx) => {
    return cssStandards({
      parser: false,
      webpack: ctx
    })
  },
  babel: {
    presets: [latest]
  }
}

**Pull request merged**
